// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBAvqKUiVFdlBOL5LBI6fA_qTz2H6J7NAQ',
    appId: '1:897665279105:web:bf96e1290097b28d5a5980',
    messagingSenderId: '897665279105',
    projectId: 'smartsapi',
    authDomain: 'smartsapi.firebaseapp.com',
    databaseURL: 'https://smartsapi-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'smartsapi.firebasestorage.app',
    measurementId: 'G-K1KG8171WQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBANsmfeok-zXq-PvIWHPhrBl5CAW5xs_I',
    appId: '1:897665279105:android:a07a40191eb19e035a5980',
    messagingSenderId: '897665279105',
    projectId: 'smartsapi',
    databaseURL: 'https://smartsapi-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'smartsapi.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBSxCZNTeORO9GUfQG3vrxzq45Vb1aqi7w',
    appId: '1:897665279105:ios:8dd392c04421d7a75a5980',
    messagingSenderId: '897665279105',
    projectId: 'smartsapi',
    databaseURL: 'https://smartsapi-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'smartsapi.firebasestorage.app',
    iosBundleId: 'com.example.front',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBSxCZNTeORO9GUfQG3vrxzq45Vb1aqi7w',
    appId: '1:897665279105:ios:8dd392c04421d7a75a5980',
    messagingSenderId: '897665279105',
    projectId: 'smartsapi',
    databaseURL: 'https://smartsapi-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'smartsapi.firebasestorage.app',
    iosBundleId: 'com.example.front',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBAvqKUiVFdlBOL5LBI6fA_qTz2H6J7NAQ',
    appId: '1:897665279105:web:9af9d74eb88e565f5a5980',
    messagingSenderId: '897665279105',
    projectId: 'smartsapi',
    authDomain: 'smartsapi.firebaseapp.com',
    databaseURL: 'https://smartsapi-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'smartsapi.firebasestorage.app',
    measurementId: 'G-QP5GZC2DLB',
  );
}
